FROM golang:1.24.3
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
# Removido: RUN go install github.com/air-verse/air@latest

# Criar diretório para build
RUN mkdir -p /app/bin 

COPY . .
EXPOSE 8080

# Comando simples que compila e executa
CMD ["sh", "-c", "go build -o ./bin/server ./cmd/server/main.go && ./bin/server"]