version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: appmercado-backend-dev
    volumes:
      - .:/app  # Mapeia o código local para o container
      - /app/bin # Volume anônimo para os binários
    ports:
      - "8080:8080"
    networks:
      - appmercado-net