version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev # Using Dockerfile.dev for development
    container_name: appmercado-backend-dev # Using dev container name
    env_file:
      - .env
    volumes:
      - .:/app  # Mapeia o código local para o container
      - /app/bin # Volume anônimo para os binários
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - appmercado-net

  postgres:
    image: postgres:14
    container_name: appmercado-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - appmercado-net

networks:
  appmercado-net:

volumes:
  postgres_data: