version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev # Using Dockerfile.dev for development
    container_name: appmercado-backend-dev # Using dev container name
    env_file:
      - .env
    volumes:
      - .:/app  # Mapeia o código local para o container
      - /app/bin # Volume anônimo para os binários
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - appmercado-net

  postgres:
    image: postgres:14
    container_name: appmercado-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - appmercado-net
    # Adiciona healthcheck para garantir que o postgres está pronto antes do pgAdmin tentar conectar
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: appmercado-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - appmercado-net

networks:
  appmercado-net:

volumes:
  postgres_data:
  pgadmin_data: