# Dockerfile.dev - Desenvolvimento com Hot Reloading (Air)
FROM golang:1.24.3 AS builder
WORKDIR /app

# Copiar os arquivos de configuração do Go
COPY go.mod go.sum ./
RUN go mod tidy && go mod download

# Instala o Air (Hot Reloading)
RUN go install github.com/air-verse/air@latest

# Copia todos os arquivos do projeto
COPY . .

# Exposição da porta do servidor
EXPOSE 8080

# Comando para iniciar o servidor com Air
CMD ["air"]
